---
- name: hosts | names in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ init_host.ip }} {{ init_host.names | join(' ') }}"
    regexp: "^{{ init_host.ip | regex_escape }}"
  loop: "{{ etc_hosts }}"
  loop_control:
    loop_var: init_host
