#!/usr/bin/zsh

gh auth status


# Set the repository (owner/repo)
REPO="rafikbahri/aws-infra"

# Main branch protection
gh api \
  --method PUT \
  "repos/${REPO}/branches/main/protection" \
  -f required_status_checks='{"strict": true, "contexts": ["continuous-integration"]}' \
  -f enforce_admins=true \
  -f required_pull_request_reviews='{"dismissal_restrictions": {}, "dismiss_stale_reviews": true, "require_code_owner_reviews": true, "required_approving_review_count": 1}' \
  -f restrictions=null \
  -f allow_force_pushes=false \
  -f allow_deletions=false

# Verify 
gh api "repos/${REPO}/branches/main/protection"