---
- name: Ansible playbook test
  hosts: bastions
  pre_tasks:
    - name: Wait for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
  tasks:
    - name: Test
      ansible.builtin.debug:
        msg: "This test is to check SSH connectivity"
