---
- name: Ansible playbook test
  hosts: bastions
  gather_facts: false
  # Wait for SSM Agent to be available on the Instance
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: eu-west-3
  pre_tasks:
    - name: Wait for connection
      wait_for_connection:

  tasks:
    - name: Test
      ansible.builtin.debug:
        msg: "This test is to check connectivity using SSM"
