---
name: CI
run-name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible/ansible-lint@main
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: .config/.markdownlint.yml
